"""Visual constants approximating the classic SAP GUI look and feel."""

APP_TITLE = "SAP Easy Access"

WINDOW_BG = "#ECECE4"
TOOLBAR_BG = "#ECE9D8"
TITLE_BG = "#005696"
TITLE_FG = "#FFFFFF"
CONTENT_BG = "#FFFFFF"
STATUSBAR_BG = "#D4D0C8"
STATUSBAR_FG = "#000000"
FIELD_LABEL_BG = "#D4D0C8"
BUTTON_RAISED = "#ECE9D8"
HEADER_BG = "#005696"
HEADER_FG = "#FFFFFF"
LINK_FG = "#0000CC"
REQUIRED_BG = "#FFFFCC"
GRID_HEADER_BG = "#D9E4EC"
GRID_ROW_ALT_BG = "#F2F6F9"
GROUPBOX_BORDER = "#ABABAB"
STATUS_OK = "#2E8B2E"
STATUS_ERR = "#C22222"
STATUS_NEUTRAL = "#8C8C8C"

FONT_NORMAL = ("Tahoma", 10)
FONT_SMALL = ("Tahoma", 9)
FONT_BOLD = ("Tahoma", 10, "bold")
FONT_HEADER = ("Tahoma", 11, "bold")
